[2024-08-31T00:59:31.599+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T00:59:31.654+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T00:59:31.676+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T00:59:31.678+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-31T00:59:31.710+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-11 00:00:00+00:00
[2024-08-31T00:59:31.724+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=707) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T00:59:31.727+0000] {standard_task_runner.py:64} INFO - Started process 730 to run task
[2024-08-31T00:59:31.727+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpk7vrudks']
[2024-08-31T00:59:31.734+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask extract_data
[2024-08-31T00:59:31.842+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [running]> on host ad3e56ef573e
[2024-08-31T00:59:32.134+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-11T00:00:00+00:00'
[2024-08-31T00:59:32.137+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T00:59:32.140+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T00:59:32.141+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T00:59:32.166+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-11T00:00:00+00:00, execution_date=20230411T000000, start_date=20240831T005931, end_date=20240831T005932
[2024-08-31T00:59:32.203+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task extract_data (No module named 'src'; 730)
[2024-08-31T00:59:32.268+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T00:59:32.293+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-31T01:55:41.037+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T01:55:41.122+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T01:55:41.168+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [queued]>
[2024-08-31T01:55:41.170+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-08-31T01:55:41.224+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-11 00:00:00+00:00
[2024-08-31T01:55:41.256+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=595) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T01:55:41.260+0000] {standard_task_runner.py:64} INFO - Started process 624 to run task
[2024-08-31T01:55:41.264+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-11T00:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpuf24vtm8']
[2024-08-31T01:55:41.271+0000] {standard_task_runner.py:91} INFO - Job 59: Subtask extract_data
[2024-08-31T01:55:41.509+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-11T00:00:00+00:00 [running]> on host dde48ad7e5a8
[2024-08-31T01:55:41.796+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-11T00:00:00+00:00'
[2024-08-31T01:55:41.800+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T01:55:41.809+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T01:55:41.813+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T01:55:41.863+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-11T00:00:00+00:00, execution_date=20230411T000000, start_date=20240831T015541, end_date=20240831T015541
[2024-08-31T01:55:41.943+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 59 for task extract_data (No module named 'src'; 624)
[2024-08-31T01:55:42.008+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T01:55:42.082+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T01:55:42.091+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
