[2024-08-31T00:59:45.308+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T00:59:45.374+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2024-08-31T00:59:45.403+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2024-08-31T00:59:45.405+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T00:59:45.457+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-30 00:00:00+00:00
[2024-08-31T00:59:45.484+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=759) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T00:59:45.488+0000] {standard_task_runner.py:64} INFO - Started process 785 to run task
[2024-08-31T00:59:45.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-30T00:00:00+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpjzgcqsvg']
[2024-08-31T00:59:45.495+0000] {standard_task_runner.py:91} INFO - Job 75: Subtask extract_data
[2024-08-31T00:59:45.621+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-30T00:00:00+00:00 [running]> on host ad3e56ef573e
[2024-08-31T00:59:45.820+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-30T00:00:00+00:00'
[2024-08-31T00:59:45.824+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T00:59:45.827+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T00:59:45.828+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T00:59:45.854+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-30T00:00:00+00:00, execution_date=20230430T000000, start_date=20240831T005945, end_date=20240831T005945
[2024-08-31T00:59:45.884+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 75 for task extract_data (No module named 'src'; 785)
[2024-08-31T00:59:45.947+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T00:59:45.998+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T00:59:46.002+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-31T01:55:56.860+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T01:55:56.930+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2024-08-31T01:55:56.966+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-04-30T00:00:00+00:00 [queued]>
[2024-08-31T01:55:56.968+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T01:55:57.353+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-30 00:00:00+00:00
[2024-08-31T01:55:57.373+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=655) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T01:55:57.378+0000] {standard_task_runner.py:64} INFO - Started process 694 to run task
[2024-08-31T01:55:57.378+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-04-30T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpjk9c_8j2']
[2024-08-31T01:55:57.384+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask extract_data
[2024-08-31T01:55:57.507+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-04-30T00:00:00+00:00 [running]> on host dde48ad7e5a8
[2024-08-31T01:55:57.736+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-04-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-04-30T00:00:00+00:00'
[2024-08-31T01:55:57.740+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T01:55:57.745+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T01:55:57.746+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T01:55:57.774+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-04-30T00:00:00+00:00, execution_date=20230430T000000, start_date=20240831T015556, end_date=20240831T015557
[2024-08-31T01:55:57.812+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 77 for task extract_data (No module named 'src'; 694)
[2024-08-31T01:55:57.877+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T01:55:57.939+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T01:55:57.943+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
