[2024-08-31T00:59:47.386+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T00:59:47.433+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2024-08-31T00:59:47.454+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2024-08-31T00:59:47.455+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T00:59:47.486+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-05-05 00:00:00+00:00
[2024-08-31T00:59:47.500+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=777) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T00:59:47.503+0000] {standard_task_runner.py:64} INFO - Started process 794 to run task
[2024-08-31T00:59:47.503+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-05-05T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpspdd4ug_']
[2024-08-31T00:59:47.508+0000] {standard_task_runner.py:91} INFO - Job 80: Subtask extract_data
[2024-08-31T00:59:47.598+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-05-05T00:00:00+00:00 [running]> on host ad3e56ef573e
[2024-08-31T00:59:47.794+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-05T00:00:00+00:00'
[2024-08-31T00:59:47.797+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T00:59:47.801+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T00:59:47.802+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T00:59:47.827+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-05-05T00:00:00+00:00, execution_date=20230505T000000, start_date=20240831T005947, end_date=20240831T005947
[2024-08-31T00:59:47.853+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 80 for task extract_data (No module named 'src'; 794)
[2024-08-31T00:59:47.880+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T00:59:47.898+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-31T01:55:59.543+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T01:55:59.609+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2024-08-31T01:55:59.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-05-05T00:00:00+00:00 [queued]>
[2024-08-31T01:55:59.635+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T01:55:59.670+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-05-05 00:00:00+00:00
[2024-08-31T01:55:59.689+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=688) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T01:55:59.693+0000] {standard_task_runner.py:64} INFO - Started process 704 to run task
[2024-08-31T01:55:59.691+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-05-05T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmpebsvdzjm']
[2024-08-31T01:55:59.697+0000] {standard_task_runner.py:91} INFO - Job 82: Subtask extract_data
[2024-08-31T01:55:59.795+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-05-05T00:00:00+00:00 [running]> on host dde48ad7e5a8
[2024-08-31T01:55:59.986+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-05-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-05T00:00:00+00:00'
[2024-08-31T01:55:59.990+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T01:55:59.994+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T01:55:59.996+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T01:56:00.022+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-05-05T00:00:00+00:00, execution_date=20230505T000000, start_date=20240831T015559, end_date=20240831T015600
[2024-08-31T01:56:00.050+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 82 for task extract_data (No module named 'src'; 704)
[2024-08-31T01:56:00.110+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T01:56:00.166+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T01:56:00.170+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
