[2024-08-31T00:48:53.070+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T00:48:53.183+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2024-08-31T00:48:53.210+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2024-08-31T00:48:53.212+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T00:48:53.252+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-26 00:00:00+00:00
[2024-08-31T00:48:53.282+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T00:48:53.295+0000] {standard_task_runner.py:64} INFO - Started process 203 to run task
[2024-08-31T00:48:53.312+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-03-26T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmparwj8viy']
[2024-08-31T00:48:53.327+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask extract_data
[2024-08-31T00:48:53.799+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-03-26T00:00:00+00:00 [running]> on host ad3e56ef573e
[2024-08-31T00:48:54.457+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-26T00:00:00+00:00'
[2024-08-31T00:48:54.470+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T00:48:54.481+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T00:48:54.488+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T00:48:54.592+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-03-26T00:00:00+00:00, execution_date=20230326T000000, start_date=20240831T004853, end_date=20240831T004854
[2024-08-31T00:48:54.676+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task extract_data (No module named 'src'; 203)
[2024-08-31T00:48:54.751+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T00:48:54.818+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-08-31T01:45:07.536+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-31T01:45:07.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2024-08-31T01:45:07.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: olist_dag.extract_data scheduled__2023-03-26T00:00:00+00:00 [queued]>
[2024-08-31T01:45:07.693+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-31T01:45:07.894+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2023-03-26 00:00:00+00:00
[2024-08-31T01:45:08.188+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=192) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-31T01:45:08.192+0000] {standard_task_runner.py:64} INFO - Started process 217 to run task
[2024-08-31T01:45:08.191+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'olist_dag', 'extract_data', 'scheduled__2023-03-26T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/elt_dag.py', '--cfg-path', '/tmp/tmp_knite_t']
[2024-08-31T01:45:08.196+0000] {standard_task_runner.py:91} INFO - Job 14: Subtask extract_data
[2024-08-31T01:45:09.514+0000] {task_command.py:426} INFO - Running <TaskInstance: olist_dag.extract_data scheduled__2023-03-26T00:00:00+00:00 [running]> on host dde48ad7e5a8
[2024-08-31T01:45:11.083+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='olist_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-26T00:00:00+00:00'
[2024-08-31T01:45:11.101+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-31T01:45:11.106+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-31T01:45:11.108+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt_dag.py", line 23, in extract_data
    from src.extract import extract
ModuleNotFoundError: No module named 'src'
[2024-08-31T01:45:11.218+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=olist_dag, task_id=extract_data, run_id=scheduled__2023-03-26T00:00:00+00:00, execution_date=20230326T000000, start_date=20240831T014507, end_date=20240831T014511
[2024-08-31T01:45:11.261+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 14 for task extract_data (No module named 'src'; 217)
[2024-08-31T01:45:11.313+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-08-31T01:45:11.389+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-31T01:45:11.407+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
